-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 16:15:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор пользователя',
  `Name` VARCHAR(128) NOT NULL COMMENT 'Читаемое название чата',
  `PasswordHash` BIGINT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chats` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор чата',
  `Name` VARCHAR(128) NULL COMMENT 'Читаемое имя чата, может отсутствовать, если чат личный',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DirectChats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DirectChats` (
  `CombinedId` MEDIUMINT NOT NULL COMMENT 'Идентификатор Личного чата, полученный с помощью комбинирования двух уникальных идентификаторов пользователей по порялку `Меньший << 4 & Больший`. Используется для идентификации Личного чата между двумя пользователями, без знания главного ключа.',
  `User1Id` INT NOT NULL,
  `User2Id` INT NOT NULL,
  `Chats_Id` INT NOT NULL,
  PRIMARY KEY (`Chats_Id`),
  INDEX `fk_DirectChats_Chats1_idx` (`Chats_Id` ASC) VISIBLE,
  UNIQUE INDEX `CombinedId_UNIQUE` (`CombinedId` ASC) VISIBLE,
  CONSTRAINT `fk_DirectChats_Chats1`
    FOREIGN KEY (`Chats_Id`)
    REFERENCES `mydb`.`Chats` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Messages` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор сообщения',
  `Chats_Id` INT NOT NULL COMMENT 'Внешний ключ чата, которому принадлежит сообщение',
  `Text` VARCHAR(1024) NULL COMMENT 'Текстовое содержимое сообщения',
  `Users_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Messages_Chats1_idx` (`Chats_Id` ASC) VISIBLE,
  INDEX `fk_Messages_Users1_idx` (`Users_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_Chats1`
    FOREIGN KEY (`Chats_Id`)
    REFERENCES `mydb`.`Chats` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Users1`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `mydb`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Chats` (
  `Users_Id` INT NOT NULL,
  `Chats_Id` INT NOT NULL,
  PRIMARY KEY (`Users_Id`, `Chats_Id`),
  INDEX `fk_Users_has_Chats_Chats1_idx` (`Chats_Id` ASC) VISIBLE,
  INDEX `fk_Users_has_Chats_Users_idx` (`Users_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Chats_Users`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `mydb`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Chats_Chats1`
    FOREIGN KEY (`Chats_Id`)
    REFERENCES `mydb`.`Chats` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
